/**
 * Hand-written one-line notes for ARAM: Mayhem augments (5–12 words: why/when an augment is good)
 * plus the champion archetypes it fits. Keyed by the augment platform id used by the game client.
 *
 * Fit tags: ap · ad · crit · onhit (attack speed / on-hit users) · tank · sup (healers & shielders) · any
 */
export type AugmentFit = 'ap' | 'ad' | 'crit' | 'onhit' | 'tank' | 'sup' | 'any'

export const AUGMENT_NOTES: Record<number, [string, AugmentFit[]]> = {
  1001: ["Stacks fast in teamfights – tanks and bruisers become unkillable", ['tank', 'ad']],
  1002: ['Item actives on half cooldown – great with Zhonya/Stopwatch/Everfrost', ['any']],
  1004: ['No ultimate, but huge ability damage – best for basic-ability champs', ['ap', 'ad', 'sup']],
  1005: ['Stronger heals and shields on low allies – enchanter pick', ['sup']],
  1006: ['Master Yi-style untargetable dash – great for melee divers', ['ad', 'onhit']],
  1007: ['Flat AD boost – simple, reliable damage for AD champions', ['ad']],
  1011: ['Ult makes you invulnerable – dive in and survive', ['any']],
  1013: ['Lots of health for less damage – good on tanks and supports', ['tank', 'sup']],
  1015: ['Your healing also burns enemies – great on sustain champions', ['tank', 'sup']],
  1018: ['Shield on every CC – tanks with hard CC love it', ['tank']],
  1019: ['Dash abilities come back much faster – mobility champs only', ['ad', 'ap']],
  1020: ['Emergency heal when low – solid survivability for anyone', ['any']],
  1022: ['Plain attack speed – strong for auto-attackers', ['onhit', 'crit']],
  1025: ['Explode on death – punishes dives, weak if you rarely die', ['tank']],
  1026: ['Bonus damage when faster – pair with movement speed', ['ad', 'onhit']],
  1027: ['Dashes leave explosive trails – extra damage for mobile champs', ['ad', 'ap']],
  1028: ['Shreds armor and MR – amplifies your whole team', ['any']],
  1029: ['Abilities apply on-hit – broken with Nashor/Kraken/BotRK', ['ap', 'onhit']],
  1030: ['Ability Haste from AP – mages spam abilities nonstop', ['ap']],
  1034: ['Spell shield blocks key CC or hooks – safe pick', ['any']],
  1036: ['Infinite stacking burn on attacks – devastating in long fights', ['onhit']],
  1037: ['More heal and shield power – core for enchanters', ['sup']],
  1038: ['First Strike plus Dark Harvest – huge burst for poke', ['ap', 'ad']],
  1041: ['Big health and adaptive force boost – good on everyone', ['any']],
  1044: ['Stronger slows – kiting and peel become much easier', ['ap', 'sup']],
  1045: ['Burns lower your cooldowns – great for DoT mages', ['ap']],
  1046: ['Extra damage on every hit – reliable burst for anyone', ['any']],
  1047: ['Free crit chance – finish crit builds earlier', ['crit']],
  1048: ['Abilities can crit – absurd burst for AP casters', ['ap']],
  1051: ['Every 4th attack fires missiles – strong for attack speed users', ['onhit']],
  1053: ['Random buff on each revive – fun, but inconsistent', ['any']],
  1054: ['Attacks give AP, spells give AD – hybrid champs only', ['onhit', 'ap']],
  1056: ['Converts mana into health – great on mana-heavy tanks', ['tank', 'ap']],
  1057: ['Free shield out of combat – good for poke wars', ['any']],
  1058: ['On-hit cuts cooldowns – perfect for spell-weaving fighters', ['onhit', 'ad']],
  1060: ['Health and mana regen – sustain through long ARAM fights', ['any']],
  1061: ['Auto-casting boomerang – free extra damage, no effort', ['any']],
  1062: ['Several random dragon souls – strong value for anyone', ['any']],
  1063: ['Armor and MR after dashes – durable divers', ['ad', 'tank']],
  1064: ['Massive regen at low health – tanks outlast everyone', ['tank']],
  1066: ['Auto-cast slash with max-health damage and healing', ['ad', 'tank']],
  1067: ['Heal on ability cast – sustain for spammable spells', ['any']],
  1068: ['Flat Ability Haste – more spells, always useful', ['any']],
  1071: ['More attack range – safer and stronger auto-attacking', ['onhit', 'crit']],
  1072: ['Marks enemies for bonus ally damage – great team burst', ['sup', 'ap']],
  1073: ['Speed after dashes or stealth – slippery assassins', ['ad']],
  1074: ['Attacks shrink enemy damage – anti-carry peel', ['onhit', 'sup']],
  1076: ['Buffing allies damages enemies – enchanter damage source', ['sup']],
  1077: ['Crit lifesteal plus crit chance – sustain for crit carries', ['crit']],
  1079: ['Lethal Tempo plus Conqueror – huge for extended fights', ['onhit', 'ad']],
  1080: ['Crit chance also reduces damage taken – crit bruisers', ['crit', 'tank']],
  1081: ['Speed from attacks turns into attack speed – kiting champs', ['onhit']],
  1084: ['Armor and magic pen – pure damage increase', ['ap', 'ad']],
  1087: ['Attacks hit a second target – great for on-hit carries', ['onhit', 'crit']],
  1088: ['Cast your ultimate twice – huge on game-changing ults', ['any']],
  1092: ['DoTs and items can crit – strong for burn champions', ['ap', 'crit']],
  1095: ['Heals and shields grant resistances – enchanter frontline', ['sup']],
  1097: ['Flat AP – simple, reliable damage for mages', ['ap']],
  1098: ['Speed from Ability Haste – kite and dodge skillshots', ['ap', 'sup']],
  1103: ['Q cooldown slashed – great if Q is your main spell', ['any']],
  1104: ['Stronger summons – pets and minions champs only', ['ap']],
  1105: ['Bonus speed out of combat – reposition quickly', ['any']],
  1112: ['CC immunity after ult – dive without being stopped', ['tank', 'ad']],
  1113: ['Long-range hits refund cooldown – poke artillery', ['ap']],
  1115: ['Big attack range boost – marksmen poke from safety', ['crit', 'onhit']],
  1116: ['Multiple Flash charges – escape or engage anytime', ['any']],
  1118: ['Heals and shields can crit – crit enchanters only', ['sup', 'crit']],
  1129: ['Attacks scale with AP – on-hit mages love it', ['ap', 'onhit']],
  1133: ['Abilities fire true-damage missiles – top burst for spammy casters', ['ap']],
  1134: ['Ranged becomes melee with huge stats – bruiser transformation', ['ad', 'ap']],
  1136: ['Stacking force from CC – snowballs with hard CC', ['tank', 'sup']],
  1138: ['Omnivamp – sustain for any damage dealer', ['ad', 'ap']],
  1141: ['Stronger heals on allies – pure enchanter value', ['sup']],
  1149: ['Aftershock plus Glacial – tanky engager kit', ['tank']],
  1150: ['W cooldown slashed – great if W is your key spell', ['any']],
  1151: ['E cooldown slashed – great if E is your key spell', ['any']],
  1152: ['Heartsteel stacks multiplied – enormous health late', ['tank']],
  1154: ['Takedown quest for Golden Spatula – huge late reward', ['any']],
  1156: ['Free Rod, quest into Wooglet’s – strong AP scaling', ['ap']],
  1170: ['Attack range boost – safer damage for marksmen', ['crit', 'onhit']],
  1180: ['Big shield from AP – mages become tanky', ['ap']],
  1181: ['Attacks deal max-health damage – health-stacking tanks', ['tank']],
  1187: ['Flash damages and slows – aggressive engage tool', ['any']],
  1194: ['Ultimate polymorphs enemies – massive CC on AoE ults', ['ap', 'sup']],
  1195: ['Tiny and fast with bonus damage vs big targets', ['ad', 'onhit']],
  1204: ['More permanent stacks – Veigar, Nasus, Senna, Sion love it', ['any']],
  1205: ['Converts AD into AP – for AP champs with AD items', ['ap']],
  1206: ['Converts AP into AD – for AD champs with AP items', ['ad']],
  1211: ['Stores damage after ult, then detonates – burst assassins', ['ad', 'ap']],
  1214: ['Spin abilities hit harder and faster – Garen, Kat, Mordekaiser', ['ad', 'ap']],
  1220: ['Attacks fire missiles – strong for ranged carries', ['crit', 'onhit']],
  1225: ['Extra on-hit bolt plus attack speed – on-hit carries', ['onhit']],
  1237: ['Random Gold augment – gamble when options are weak', ['any']],
  1238: ['Random Prismatic augment – usually a free upgrade', ['any']],
  1243: ['Several random augments – high variance, high value', ['any']],
  1301: ['Periodic team-wide invulnerability – wins teamfights', ['sup', 'tank']],
  1305: ['Speed and slow resist – good for everyone in ARAM', ['any']],
  1308: ['Orbiting flames for passive damage and speed', ['ap']],
  1310: ['Deceive and death explosion – trolly, weak in ARAM', ['ad']],
  1311: ['Mana doubles as power – mana-stackers scale massively', ['ap']],
  1314: ['Force burst when shielded – great with shield items', ['any']],
  1315: ['Shield after dashes – survivability for divers', ['ad']],
  1318: ['Zhonya’s on short cooldown – mages become hard to kill', ['ap']],
  1319: ['Gold from Sunfire/Hollow burns – tanks build faster', ['tank']],
  1320: ['Better Collector executes and gold – snowball crit carries', ['crit']],
  1322: ['Speed and attack speed on takedown – chain resets', ['onhit', 'ad']],
  1323: ['CC summons comets – free damage for CC-heavy kits', ['tank', 'sup']],
  1324: ['Heal/shield power from resists – tanky enchanters', ['sup', 'tank']],
  1325: ['Less health, extra true damage – glass cannon assassins', ['ad', 'ap']],
  1326: ['Invisible after takedowns – reset-happy assassins', ['ad']],
  1327: ['Resists on CC – tanks with lots of CC', ['tank']],
  1328: ['Crits stack attack speed – crit marksmen', ['crit']],
  1329: ['Giant snowball that knocks up – great engage for anyone', ['any']],
  1331: ['Heal/shield power and ally teleport – enchanter mobility', ['sup']],
  1332: ['AP, speed and vamp from missing health – risky mages', ['ap']],
  1333: ['Huge shield and speed when low – escapes almost anything', ['any']],
  1334: ['Snowball hits create a damaging slow zone', ['any']],
  1335: ['Extra damage that pays gold – snowball your items', ['any']],
  1336: ['Gold and random crit damage with Infinity Edge', ['crit']],
  1337: ['Take the transport with a legendary for a Prismatic', ['any']],
  1343: ['Upgraded boots now, quest for Jarvan’s boots', ['any']],
  1344: ['Big shield, vamp and speed after ult – divers love it', ['ad', 'tank']],
  1345: ['Takedowns explode for current-health damage – teamfight chains', ['any']],
  1346: ['Big omnivamp, no ally healing – self-sustain carries', ['ad', 'ap']],
  1347: ['Barrier and Ghost in one spell – flexible safety', ['any']],
  1348: ['Second Flash plus summoner haste – outplay tool', ['any']],
  1349: ['Ult resets basic abilities – burst combo champions', ['ap', 'ad']],
  1353: ['Grows bigger and tankier with takedowns', ['tank', 'ad']],
  1356: ['Crits fire magic missiles – crit carries', ['crit']],
  1358: ['Snowball bounces off walls for more damage', ['any']],
  1361: ['Bami’s now, quest into Void Immolation – burn tanks', ['tank']],
  1373: ['Takedowns shrink you and add haste plus speed', ['any']],
  1375: ['Permanent health on CC – tanks scale all game', ['tank']],
  1379: ['Attack speed and stronger Blossoming Dawn heals', ['onhit']],
  1384: ['Free gold now – rush your core item', ['any']],
  1386: ['Grapple swing – mobility trick, needs practice', ['ad']],
  1388: ['Ability Haste that keeps growing with takedowns', ['any']],
  1389: ['Adaptive force and empowered minions – push waves', ['any']],
  1390: ['Permanent AP stacks from spell hits – poke mages scale', ['ap']],
  1392: ['Invulnerable snowball dash – engage for free', ['any']],
  1401: ['Summoner spell knock-up plus health – tank engage', ['tank']],
  1402: ['Many stat anvils plus extra rerolls next pick', ['any']],
  1403: ['Several stat anvils – solid raw stats', ['any']],
  1404: ['A few stat anvils – filler if nothing fits', ['any']],
  1413: ['Ult taunts and grants damage reduction – tank engage', ['tank']],
  1415: ['Spells fire extra missiles – great for spammy casters', ['ap']],
  1416: ['Periodic chain lightning with slow – AoE damage', ['any']],
  1420: ['Auto heals, shields and speed – team sustain', ['sup']],
  1421: ['Auto-cast charm dash – surprise engage', ['any']],
  1996: ['Spellblade hits harder and heals – Sheen users', ['ad', 'ap']],
  2004: ['Healing allies builds an executing shockwave', ['sup']],
  2005: ['Style meter triggers free Inferno – aggressive fighters', ['ad']],
  2006: ['Executes low enemies with knockback and heal', ['any']],
  2007: ['Drains your health for true damage – risky', ['ad', 'ap']],
  2009: ['Crit and attack speed – crit carries', ['crit']],
  2010: ['Crits apply on-hit twice – crit on-hit hybrids', ['crit', 'onhit']],
  2016: ['On-hit mana burst that can crit – mana carries', ['onhit']],
  2018: ['Attack speed becomes haste plus CDR – pure casters', ['ap', 'sup']],
  2024: ['Haste from crit chance – crit champs with spells', ['crit']],
  2026: ['Speed toward low enemies – secure kills', ['any']],
  2031: ['Tibbers drops on death – fun death insurance', ['any']],
  2032: ['A shark bites enemies after you die', ['any']],
  2034: ['Sharks circle your snowball – slow and damage', ['any']],
  2042: ['Damage boost from brush – situational on ARAM maps', ['any']],
  2043: ['Big heal in brush – situational sustain', ['any']],
  2046: ['Feed poros, unlock a poro stampede – long quest', ['any']],
  2054: ['Spell hits two extra targets – AoE value', ['any']],
  2055: ['Quest adds missiles to your spell – poke mages', ['ap']],
  2062: ['Spell recast by a clone – double damage', ['any']],
  2063: ['Zone that isolates enemies – pick-off tool', ['any']],
  2064: ['Spell also dashes you – extra mobility', ['any']],
  2065: ['Spell fears nearby enemies – extra CC', ['any']],
  2072: ['Missile splits on hit – more poke', ['any']],
  2073: ['Spell hits heal you – sustain in long fights', ['any']],
  2076: ['Resists when your spell hits – bruiser durability', ['tank', 'ad']],
  2077: ['CC spell deals extra damage and heals', ['any']],
  2078: ['Knockbacks chain into knock-ups – wombo combos', ['any']],
  2080: ['Recast snowball knocks up and back – engage', ['any']],
  2082: ['You heal from nearby healing – anti-sustain', ['any']],
  2083: ['Teeth grant permanent lethality and magic pen', ['ad', 'ap']],
  2087: ['Casts refund other cooldowns – spell-spamming casters', ['ap']],
  2088: ['Snowball with 100 haste and extra damage', ['any']],
  2089: ['Takedowns drop gold coins for your team', ['any']],
  2091: ['Auto-cast axe with healing – sustained bruiser damage', ['ad', 'tank']],
  2095: ['Nearby kills drop stat anvils – snowball stats', ['any']],
  2096: ['Range and attack speed during spell – marksmen', ['onhit', 'crit']],
  2097: ['Dash leaves a slowing void zone', ['any']],
  2098: ['Hit vitals for true damage, heal and speed', ['ad', 'onhit']],
  2099: ['Enemy essences reset basic cooldowns', ['any']],
  2100: ['Quest: spell hits grant it ability haste', ['any']],
  2102: ['Health-scaling burn aura that grows – tank damage', ['tank']],
  2103: ['Snipe quest unlocks meteors – long-range poke', ['ap']],
  2104: ['Healing builds a bomb that heals your team', ['sup']],
  2107: ['Revive empowered after dealing damage – second life', ['any']],
  2108: ['Your heals also heal over time – enchanters', ['sup']],
  2109: ['Recast spell to explode and return – safe trades', ['any']],
  2111: ['Empowered spell hits deal splash damage', ['ad']],
  2115: ['Tether and pull all nearby enemies – wombo engage', ['tank']],
  2116: ['Quest: spell damage increases permanently', ['any']],
  2118: ['Ultimate on a very short cooldown – ult-reliant champs', ['any']],
  2119: ['Recall into a long-range cannon launch', ['any']],
  2123: ['Other abilities reset this spell – spam it', ['any']],
  2125: ['Movement speed while spell is active', ['any']],
  2126: ['On-hit during spell lowers its cooldown', ['onhit']],
  2127: ['Items and augments deal more damage', ['any']],
  2128: ['Burns and DoTs generate gold – DoT mages', ['ap']],
  2129: ['Spell deals area damage around its impact', ['any']],
  2131: ['Shield while channeling – channel champs only', ['ap']],
  2132: ['Omnivamp – sustain for any damage dealer', ['ad', 'ap']],
  2133: ['Heal an ally, empower your next attack', ['sup']],
  2134: ['Ult spawns a haste zone firing missiles', ['any']],
  2135: ['Nails accumulate damage and execute', ['onhit']],
  2136: ['Spell damage grows with Friendship stacks', ['any']],
  2137: ['Allies give you shields and speed', ['any']],
  2138: ['Adaptive resistances when your spell hits', ['tank']],
  2139: ['Taking damage fires slowing needles – tanks', ['tank']],
  2140: ['Spell hits cleave, more lifesteal – Hydra users', ['ad']],
  2141: ['Quest for Ultra Hydra – long-term AD bruiser scaling', ['ad']],
  2143: ['Sundered Sky crits more often and heals', ['ad']],
  2144: ['Stronger shields on low-health allies', ['sup']],
  2148: ['Spell applies on-hit twice', ['onhit']],
  2157: ['Death’s Dance absorbs more and heals', ['ad']],
  12317: ['Turns all your augments Prismatic – late-game gamble', ['any']]
}
